// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pxtjqcuafxoswznjnkgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB4dGpxY3VhZnhvc3d6bmpua2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MTg5MDMsImV4cCI6MjA2NTI5NDkwM30.9wVs_gA0RimZvLw-QQBUEYfsnIk4PaFBTXgIHf2LkFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);